<?php
	include("conexion.php");
	function registraAreas(){
		mysql_query("insert into area (nom_a) values ('CALCULO')");
        mysql_query("insert into area (nom_a) values ('FISICO-QUIMICA')");
        mysql_query("insert into area (nom_a) values ('CONSTRUCCION')");
        mysql_query("insert into area (nom_a) values ('TECNOLOGIA')");
        mysql_query("insert into area (nom_a) values ('GEOASTRONOMICA')");
        mysql_query("insert into area (nom_a) values ('BIOAGROPECUARIA')");
        mysql_query("insert into area (nom_a) values ('BIOSANITARIA')");
        mysql_query("insert into area (nom_a) values ('ASISTENCIA EDUCACIONAL')");
        mysql_query("insert into area (nom_a) values ('JURIDICO-POLITICA')");
        mysql_query("insert into area (nom_a) values ('ECONOMICO ADMINISTRATIVA')");
        mysql_query("insert into area (nom_a) values ('COMUNICACION SOCIAL')");
        mysql_query("insert into area (nom_a) values ('HUMANISTICA CULTURAL')");
        mysql_query("insert into area (nom_a) values ('ARTISTICO-PLASTICA')");
        mysql_query("insert into area (nom_a) values ('ARTISTICO-MUSICAL')");
        mysql_query("insert into area (nom_a) values ('LENGUAS EXTRANJERAS')"); 
	}

	function registraPuntaje_percentil(){
			mysql_query("insert into puntaje_percentil(id_area,puntaje,sexo,percentil) values (1,27,'M',99)");
            mysql_query("insert into puntaje_percentil(id_area,puntaje,sexo,percentil) values (2,30,'M',99)");
            mysql_query("insert into puntaje_percentil(id_area,puntaje,sexo,percentil) values (3,30,'M',99)");
            mysql_query("insert into puntaje_percentil(id_area,puntaje,sexo,percentil) values (4,27,'M',99)");
            mysql_query("insert into puntaje_percentil(id_area,puntaje,sexo,percentil) values (5,30,'M',99)");
            mysql_query("insert into puntaje_percentil(id_area,puntaje,sexo,percentil) values (6,33,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,29,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,30,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,27,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,33,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,33,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,33,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,33,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,30,'M',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,24,'M',99)");
            //percentil 95 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,27,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,29,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,29,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,26,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,30,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,33,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,27,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,29,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,25,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,33,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,32,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,31,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,31,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,29,'M',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,28,'M',95)");
            //percentil 90 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,27,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,28,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,27,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,25,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,29,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,33,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,25,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,27,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,24,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,31,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,30,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,29,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,29,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,27,'M',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,22,'M',90)");
           //percentil 80 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,26,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,27,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,24,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,24,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,27,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,30,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,22,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,25,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,21,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,28,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,28,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,26,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,26,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,24,'M',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,20,'M',80)");
            //percentil 75 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,25,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,26,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,23,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,23,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,26,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,29,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,20,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,24,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,20,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,27,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,27,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,25,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,25,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,23,'M',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,20,'M',75)");
            //percentil 70 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,24,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,25,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,22,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,22,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,25,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,28,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,19,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,23,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,19,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,26,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,26,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,24,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,24,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,22,'M',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,19,'M',70)");
            //percentil 60 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,22,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,23,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,20,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,20,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,23,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,25,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,18,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,21,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,17,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,23,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,25,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,22,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,23,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,20,'M',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,18,'M',60)");
            //percentil 50 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,20,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,21,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,19,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,19,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,22,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,24,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,16,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,19,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,15,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,21,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,23,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,20,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,21,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,18,'M',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,17,'M',50)");
            //percentil 40 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,18,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,19,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,18,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,18,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,21,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,22,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,15,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,17,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,18,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,19,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,22,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,18,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,19,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,17,'M',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,16,'M',40)");
           //percentil 25 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,18,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,16,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,14,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,15,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,19,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,19,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,13,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,14,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,12,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,15,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,19,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,15,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,17,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,13,'M',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,14,'M',25)");
           //percentil 10 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,10,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,12,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,11,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,11,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,15,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,15,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,11,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,11,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,10,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,12,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,15,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,13,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,14,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,11,'M',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,11,'M',10)");
           //percentil 5 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,9,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,11,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,10,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,10,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,13,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,14,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,10,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,10,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,9,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,11,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,14,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,12,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,13,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,10,'M',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,9,'M',5)");
          //percentil 1 sexo 'M'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,9,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,10,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,10,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,9,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,11,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,11,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,10,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,10,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,9,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,11,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,11,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,11,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,11,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,10,'M',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,8,'M',1)");
           
            
            //percentil 99 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,27,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,30,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,29,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,26,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,30,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,33,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,30,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,30,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,27,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,33,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,33,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,33,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,33,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,30,'F',99)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,24,'F',99)");
            //percentil 95 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,27,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,28,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,26,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,22,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,30,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,33,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,29,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,30,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,26,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,32,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,32,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,33,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,32,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,29,'F',95)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,24,'F',95)");
            //percentil 90 sexo 'F' 
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,26,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,26,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,24,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,20,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,29,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,32,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,28,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,29,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,25,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,31,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,30,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,32,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,31,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,28,'F',90)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,23,'F',90)");
           //percentil 80 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,24,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,23,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,21,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,18,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,27,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,30,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,25,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,28,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,22,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,26,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,28,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,29,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,30,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,25,'F',80)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,22,'F',80)");
            //percentil 75 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,23,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,22,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,20,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,17,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,26,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,29,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,24,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,28,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,21,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,25,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,28,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,28,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,29,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,23,'F',75)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,22,'F',75)");
            //percentil 70 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,21,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,21,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,19,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,16,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,26,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,28,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,23,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,27,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,20,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,23,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,27,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,27,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,28,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,22,'F',70)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,21,'F',70)");
            //percentil 60 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,18,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,19,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,17,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,14,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,24,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,25,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,21,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,26,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,18,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,21,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,25,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,25,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,26,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,20,'F',60)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,20,'F',60)");
            //percentil 50 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,16,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,18,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,15,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,13,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,22,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,24,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,20,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,25,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,17,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,19,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,24,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,23,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,25,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,19,'F',50)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,18,'F',50)");
            //percentil 40 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,13,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,16,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,14,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,12,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,20,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,22,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,18,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,23,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,15,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,17,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,23,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,21,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,23,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,17,'F',40)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,17,'F',40)");
           //percentil 25 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,11,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,13,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,12,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,11,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,17,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,19,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,15,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,20,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,13,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,14,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,20,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,18,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,20,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,14,'F',25)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,16,'F',25)");
           //percentil 10 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,9,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,11,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,10,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,9,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,14,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,15,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,12,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,15,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,10,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,12,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,16,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,14,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,16,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,12,'F',10)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,12,'F',10)");
           //percentil 5 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,9,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,10,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,10,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,9,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,13,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,11,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,13,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,10,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,11,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,11,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,13,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,14,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,11,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,10,'F',5)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,5,'F',5)");
          //percentil 1 sexo 'F'
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (1,9,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (2,10,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (3,10,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (4,9,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (5,10,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (6,11,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (7,10,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (8,10,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (9,9,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (10,11,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (11,12,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (12,11,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (13,12,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (14,10,'F',1)");
            mysql_query("insert into puntaje_percentil (id_area,puntaje,sexo,percentil) values (15,8,'F',1)");
	}
	function registraPA(){
		//calculo
            mysql_query("insert into rel_a_p values (1,4)");
            mysql_query("insert into rel_a_p values (1,17)");
            mysql_query("insert into rel_a_p values (1,26)");
            mysql_query("insert into rel_a_p values (1,62)");
            mysql_query("insert into rel_a_p values (1,111)");
            mysql_query("insert into rel_a_p values (1,114)");
            mysql_query("insert into rel_a_p values (1,135)");
            mysql_query("insert into rel_a_p values (1,144)");
            mysql_query("insert into rel_a_p values (1,146)");
            //FISICO-QUIMICA
            mysql_query("insert into rel_a_p values (2,12)");
            mysql_query("insert into rel_a_p values (2,29)");
            mysql_query("insert into rel_a_p values (2,44)");
            mysql_query("insert into rel_a_p values (2,45)");
            mysql_query("insert into rel_a_p values (2,86)");
            mysql_query("insert into rel_a_p values (2,104)");
            mysql_query("insert into rel_a_p values (2,119)");
            mysql_query("insert into rel_a_p values (2,128)");
            mysql_query("insert into rel_a_p values (2,129)");
            mysql_query("insert into rel_a_p values (2,138)");
            //CONSTRUCCION
            mysql_query("insert into rel_a_p values (3,7)");
            mysql_query("insert into rel_a_p values (3,14)");
            mysql_query("insert into rel_a_p values (3,16)");
            mysql_query("insert into rel_a_p values (3,20)");
            mysql_query("insert into rel_a_p values (3,27)");
            mysql_query("insert into rel_a_p values (3,64)");
            mysql_query("insert into rel_a_p values (3,91)");
            mysql_query("insert into rel_a_p values (3,136)");
            mysql_query("insert into rel_a_p values (3,140)");
            mysql_query("insert into rel_a_p values (3,150)");
            //TECNOLOGIA
            mysql_query("insert into rel_a_p values (4,11)");
            mysql_query("insert into rel_a_p values (4,18)");
            mysql_query("insert into rel_a_p values (4,23)");
            mysql_query("insert into rel_a_p values (4,52)");
            mysql_query("insert into rel_a_p values (4,74)");
            mysql_query("insert into rel_a_p values (4,87)");
            mysql_query("insert into rel_a_p values (4,89)");
            mysql_query("insert into rel_a_p values (4,133)");
            mysql_query("insert into rel_a_p values (4,137)");
            //GEOASTRONOMICA
            mysql_query("insert into rel_a_p values (5,15)");
            mysql_query("insert into rel_a_p values (5,37)");
            mysql_query("insert into rel_a_p values (5,54)");
            mysql_query("insert into rel_a_p values (5,57)");
            mysql_query("insert into rel_a_p values (5,96)");
            mysql_query("insert into rel_a_p values (5,99)");
            mysql_query("insert into rel_a_p values (5,109)");
            mysql_query("insert into rel_a_p values (5,123)");
            mysql_query("insert into rel_a_p values (5,124)");
            mysql_query("insert into rel_a_p values (5,132)");
            //BIOAGROPECUARIA
            mysql_query("insert into rel_a_p values (6,8)");
            mysql_query("insert into rel_a_p values (6,30)");
            mysql_query("insert into rel_a_p values (6,39)");
            mysql_query("insert into rel_a_p values (6,48)");
            mysql_query("insert into rel_a_p values (6,49)");
            mysql_query("insert into rel_a_p values (6,56)");
            mysql_query("insert into rel_a_p values (6,75)");
            mysql_query("insert into rel_a_p values (6,82)");
            mysql_query("insert into rel_a_p values (6,84)");
            mysql_query("insert into rel_a_p values (6,88)");
            mysql_query("insert into rel_a_p values (6,120)");
            //BIOSANITARIA
            mysql_query("insert into rel_a_p values (7,9)");
            mysql_query("insert into rel_a_p values (7,24)");
            mysql_query("insert into rel_a_p values (7,34)");
            mysql_query("insert into rel_a_p values (7,40)");
            mysql_query("insert into rel_a_p values (7,72)");
            mysql_query("insert into rel_a_p values (7,94)");
            mysql_query("insert into rel_a_p values (7,121)");
            mysql_query("insert into rel_a_p values (7,126)");
            mysql_query("insert into rel_a_p values (7,130)");
            mysql_query("insert into rel_a_p values (7,134)");
            //ASISTENCIA EDUCACIONAL
            mysql_query("insert into rel_a_p values (8,21)");
            mysql_query("insert into rel_a_p values (8,38)");
            mysql_query("insert into rel_a_p values (8,92)");
            mysql_query("insert into rel_a_p values (8,97)");
            mysql_query("insert into rel_a_p values (8,108)");
            mysql_query("insert into rel_a_p values (8,131)");
            mysql_query("insert into rel_a_p values (8,139)");
            mysql_query("insert into rel_a_p values (8,142)");
            mysql_query("insert into rel_a_p values (8,143)");
            mysql_query("insert into rel_a_p values (8,145)");
            //JURid_areaICO-POLITICA
            mysql_query("insert into rel_a_p values (9,3)");
            mysql_query("insert into rel_a_p values (9,6)");
            mysql_query("insert into rel_a_p values (9,22)");
            mysql_query("insert into rel_a_p values (9,42)");
            mysql_query("insert into rel_a_p values (9,58)");
            mysql_query("insert into rel_a_p values (9,100)");
            mysql_query("insert into rel_a_p values (9,105)");
            mysql_query("insert into rel_a_p values (9,117)");
            mysql_query("insert into rel_a_p values (9,148)");
            //ECONOMICO ADMINISTRATIVA
            mysql_query("insert into rel_a_p values (10,13)");
            mysql_query("insert into rel_a_p values (10,55)");
            mysql_query("insert into rel_a_p values (10,60)");
            mysql_query("insert into rel_a_p values (10,61)");
            mysql_query("insert into rel_a_p values (10,79)");
            mysql_query("insert into rel_a_p values (10,80)");
            mysql_query("insert into rel_a_p values (10,101)");
            mysql_query("insert into rel_a_p values (10,107)");
            mysql_query("insert into rel_a_p values (10,110)");
            mysql_query("insert into rel_a_p values (10,122)");
            mysql_query("insert into rel_a_p values (10,147)");
            //COMUNICACION SOCIAL
            mysql_query("insert into rel_a_p values (11,19)");
            mysql_query("insert into rel_a_p values (11,25)");
            mysql_query("insert into rel_a_p values (11,35)");
            mysql_query("insert into rel_a_p values (11,41)");
            mysql_query("insert into rel_a_p values (11,63)");
            mysql_query("insert into rel_a_p values (11,73)");
            mysql_query("insert into rel_a_p values (11,76)");
            mysql_query("insert into rel_a_p values (11,83)");
            mysql_query("insert into rel_a_p values (11,90)");
            mysql_query("insert into rel_a_p values (11,113)");
            mysql_query("insert into rel_a_p values (11,149)");
            //HUMANISTICA CULTURAL
            mysql_query("insert into rel_a_p values (12,28)");
            mysql_query("insert into rel_a_p values (12,32)");
            mysql_query("insert into rel_a_p values (12,36)");
            mysql_query("insert into rel_a_p values (12,53)");
            mysql_query("insert into rel_a_p values (12,65)");
            mysql_query("insert into rel_a_p values (12,67)");
            mysql_query("insert into rel_a_p values (12,68)");
            mysql_query("insert into rel_a_p values (12,81)");
            mysql_query("insert into rel_a_p values (12,112)");
            mysql_query("insert into rel_a_p values (12,115)");
            mysql_query("insert into rel_a_p values (12,127)");
            //ARTISTICO-PLASTICA
            mysql_query("insert into rel_a_p values (13,1)");
            mysql_query("insert into rel_a_p values (13,5)");
            mysql_query("insert into rel_a_p values (13,10)");
            mysql_query("insert into rel_a_p values (13,31)");
            mysql_query("insert into rel_a_p values (13,46)");
            mysql_query("insert into rel_a_p values (13,51)");
            mysql_query("insert into rel_a_p values (13,95)");
            mysql_query("insert into rel_a_p values (13,98)");
            mysql_query("insert into rel_a_p values (13,102)");
            mysql_query("insert into rel_a_p values (13,116)");
            mysql_query("insert into rel_a_p values (13,125)");
            //ARTISTICO-MUSICAL
            mysql_query("insert into rel_a_p values (14,2)");
            mysql_query("insert into rel_a_p values (14,50)");
            mysql_query("insert into rel_a_p values (14,70)");
            mysql_query("insert into rel_a_p values (14,71)");
            mysql_query("insert into rel_a_p values (14,77)");
            mysql_query("insert into rel_a_p values (14,78)");
            mysql_query("insert into rel_a_p values (14,85)");
            mysql_query("insert into rel_a_p values (14,106)");
            mysql_query("insert into rel_a_p values (14,118)");
            mysql_query("insert into rel_a_p values (14,141)");
            //LENGUAS EXTRANJERAS
            mysql_query("insert into rel_a_p values (15,33)");
            mysql_query("insert into rel_a_p values (15,43)");
            mysql_query("insert into rel_a_p values (15,47)");
            mysql_query("insert into rel_a_p values (15,59)");
            mysql_query("insert into rel_a_p values (15,66)");
            mysql_query("insert into rel_a_p values (15,69)");
            mysql_query("insert into rel_a_p values (15,93)");
            mysql_query("insert into rel_a_p values (15,103)");
	}
	function registrarPreguntas(){
		//Primeras 75
mysql_query("insert into test (num_preg,pregunta) values (1,'Conocer estilos de pintura contemporánea')");
mysql_query("insert into test (num_preg,pregunta) values (2,'Dirigir coros')");
mysql_query("insert into test (num_preg,pregunta) values (3,'Trabajar en estudios jurídicos')");
mysql_query("insert into test (num_preg,pregunta) values (4,'Trabajar con máquinas calculadoras')");
mysql_query("insert into test (num_preg,pregunta) values (5,'Realizar dibujos publicitarios')");
mysql_query("insert into test (num_preg,pregunta) values (6,'Trabajar en servicios diplomáticos')");
mysql_query("insert into test (num_preg,pregunta) values (7,'Planificar la construcción de obras fluviales y maritimas')");
mysql_query("insert into test (num_preg,pregunta) values (8,'Investigar la fauna y flora de una región')");
mysql_query("insert into test (num_preg,pregunta) values (9,'Extraer y restaurar dientes dañados')");
mysql_query("insert into test (num_preg,pregunta) values (10,'Realizar creaciones escultóricas')");
mysql_query("insert into test (num_preg,pregunta) values (11,'Construir prototipos de aeromodelismo en madera balsa')");
mysql_query("insert into test (num_preg,pregunta) values (12,'Organizar plantas de la industria química')");
mysql_query("insert into test (num_preg,pregunta) values (13,'Investigar el nivel de precios y procesos inflacionarios')");
mysql_query("insert into test (num_preg,pregunta) values (14,'Mantener obras viales en perfectas condiciones')");
mysql_query("insert into test (num_preg,pregunta) values (15,'Efectuar pronósticos de fenómenos meteorológicos')");
mysql_query("insert into test (num_preg,pregunta) values (16,'Construir caminos')");
mysql_query("insert into test (num_preg,pregunta) values (17,'Resolver ecuaciones matemáticas')");
mysql_query("insert into test (num_preg,pregunta) values (18,'Trabajar con equipos eléctricos')");
mysql_query("insert into test (num_preg,pregunta) values (19,'Realizar critica de espectáculos cinematográficos')");
mysql_query("insert into test (num_preg,pregunta) values (20,'Diseñar e instalar ascensores')");
mysql_query("insert into test (num_preg,pregunta) values (21,'Asesorar a alumnos sobre técnicas de estudio')");
mysql_query("insert into test (num_preg,pregunta) values (22,'Analizar audiencias y juicios')");
mysql_query("insert into test (num_preg,pregunta) values (23,'Evaluar el estado de líneas y redes eléctricas')");
mysql_query("insert into test (num_preg,pregunta) values (24,'Educar para una correcta higiene bucal')");
mysql_query("insert into test (num_preg,pregunta) values (25,'Trabajar en una agencia de noticias')");
mysql_query("insert into test (num_preg,pregunta) values (26,'Enseñar matemáticas')");
mysql_query("insert into test (num_preg,pregunta) values (27,'Asesorar en empresas constructoras')");
mysql_query("insert into test (num_preg,pregunta) values (28,'Efectuar trabajos de crítica y análisis literario')");
mysql_query("insert into test (num_preg,pregunta) values (29,'Investigar propiedades de distintos metales')");
mysql_query("insert into test (num_preg,pregunta) values (30,'Proteger especies animales en vías de extinción')");
mysql_query("insert into test (num_preg,pregunta) values (31,'Conocer técnicas y materiales de dibujo y pintura')");
mysql_query("insert into test (num_preg,pregunta) values (32,'Conocer la biografía de pensadores famosos')");
mysql_query("insert into test (num_preg,pregunta) values (33,'Pronunciar correctamente una lengua extranjera')");
mysql_query("insert into test (num_preg,pregunta) values (34,'Investigar las causas de las enfermedades cardiovasculares')");
mysql_query("insert into test (num_preg,pregunta) values (35,'Realizar análisis estadísticos de encuestas')");
mysql_query("insert into test (num_preg,pregunta) values (36,'Organizar una biblioteca')");
mysql_query("insert into test (num_preg,pregunta) values (37,'Detectar centros sísmicos')");
mysql_query("insert into test (num_preg,pregunta) values (38,'Organizar un establecimiento de educación primaria')");
mysql_query("insert into test (num_preg,pregunta) values (39,'Asesorar en quintas, granjas y viveros')");
mysql_query("insert into test (num_preg,pregunta) values (40,'Adquirir conocimientos de anatomía y fisiología')");
mysql_query("insert into test (num_preg,pregunta) values (41,'Realizar encuestas para conocer la opinión publica')");
mysql_query("insert into test (num_preg,pregunta) values (42,'Tomar declaraciones a testigos de accidente')");
mysql_query("insert into test (num_preg,pregunta) values (43,'Traducir documentos comerciales a otro idioma')");
mysql_query("insert into test (num_preg,pregunta) values (44,'Realizar análisis de productos')");
mysql_query("insert into test (num_preg,pregunta) values (45,'Investigar la constitución física-química de los minerales')");
mysql_query("insert into test (num_preg,pregunta) values (46,'Organizar visitas guiadas a museos y galerías de arte')");
mysql_query("insert into test (num_preg,pregunta) values (47,'Dar clases en un instituto de idiomas')");
mysql_query("insert into test (num_preg,pregunta) values (48,'Experimentar para desarrollar nuevas variedades de plantas')");
mysql_query("insert into test (num_preg,pregunta) values (49,'Investigar las aguas subterráneas de una región')");
mysql_query("insert into test (num_preg,pregunta) values (50,'Musicalizar obras teatrales')");
mysql_query("insert into test (num_preg,pregunta) values (51,'Diseñar stands para ferias artesanales')");
mysql_query("insert into test (num_preg,pregunta) values (52,'Realizar proyectos de electrificación rural')");
mysql_query("insert into test (num_preg,pregunta) values (53,'Trabajar en un archivo histórico')");
mysql_query("insert into test (num_preg,pregunta) values (54,'Buscar restos arqueológicos')");
mysql_query("insert into test (num_preg,pregunta) values (55,'Investigar problemas económicos nacionales e internacionales')");
mysql_query("insert into test (num_preg,pregunta) values (56,'Supervisar la producción agropecuaria')");
mysql_query("insert into test (num_preg,pregunta) values (57,'Localizar y evaluar yacimientos de minerales')");
mysql_query("insert into test (num_preg,pregunta) values (58,'Asesorar a particulares en juicio de divorcio')");
mysql_query("insert into test (num_preg,pregunta) values (59,'Realizar traducciones científicas a otro idioma')");
mysql_query("insert into test (num_preg,pregunta) values (60,'Asesorar en materia de impuestos')");
mysql_query("insert into test (num_preg,pregunta) values (61,'Supervisar las condiciones laborales de una empresa')");
mysql_query("insert into test (num_preg,pregunta) values (62,'Hacer cálculos matemáticos')");
mysql_query("insert into test (num_preg,pregunta) values (63,'Producir programas televisivos')");
mysql_query("insert into test (num_preg,pregunta) values (64,'Controlar los planos de una obra en construcción')");
mysql_query("insert into test (num_preg,pregunta) values (65,'Enseñar literatura argentina')");
mysql_query("insert into test (num_preg,pregunta) values (66,'Comunicarse con otras personas en un idioma extranjero')");
mysql_query("insert into test (num_preg,pregunta) values (67,'Investigar acontecimientos de la historia nacional')");
mysql_query("insert into test (num_preg,pregunta) values (68,'Asesorar a personas con inquietudes literarias')");
mysql_query("insert into test (num_preg,pregunta) values (69,'Desempeñar como interprete en una conferencia de prensa')");
mysql_query("insert into test (num_preg,pregunta) values (70,'Leer partituras')");
mysql_query("insert into test (num_preg,pregunta) values (71,'Concurrir a conciertos y audiciones musicales')");
mysql_query("insert into test (num_preg,pregunta) values (72,'Prescribir y controlar tratamientos dietéticos')");
mysql_query("insert into test (num_preg,pregunta) values (73,'Elaborar el guion de un audiovisual')");
mysql_query("insert into test (num_preg,pregunta) values (74,'Diseñar unidades ópticas para automóviles')");
mysql_query("insert into test (num_preg,pregunta) values (75,'Asesorar sobre el cuidado y cría de animales')");
            //segundas 75
mysql_query("insert into test (num_preg,pregunta) values (76,'Hacer notas especializadas en la radio')");
mysql_query("insert into test (num_preg,pregunta) values (77,'Enseñar técnicas de dirección orquestal')");
mysql_query("insert into test (num_preg,pregunta) values (78,'Realizar arreglos musicales')");
mysql_query("insert into test (num_preg,pregunta) values (79,'Organizar las relaciones publicas de una empresa')");
mysql_query("insert into test (num_preg,pregunta) values (80,'Realizar análisis de comercio internacional')");
mysql_query("insert into test (num_preg,pregunta) values (81,'Analizar el estilo del habla en Argentina')");
mysql_query("insert into test (num_preg,pregunta) values (82,'Asesorar sobre métodos de cultivo')");
mysql_query("insert into test (num_preg,pregunta) values (83,'Redactar anuncios publicitarios')");
mysql_query("insert into test (num_preg,pregunta) values (84,'Conocer el campo y sus tareas')");
mysql_query("insert into test (num_preg,pregunta) values (85,'Investigar los instrumentos musicales indigenas')");
mysql_query("insert into test (num_preg,pregunta) values (86,'Elaborar combustibles')");
mysql_query("insert into test (num_preg,pregunta) values (87,'Armar motores y probarlos en bancos de prueba')");
mysql_query("insert into test (num_preg,pregunta) values (88,'Conocer las especies frutícolas')");
mysql_query("insert into test (num_preg,pregunta) values (89,'Proyectar tractores y camiones')");
mysql_query("insert into test (num_preg,pregunta) values (90,'Trabajar en una revista especializada en deportes')");
mysql_query("insert into test (num_preg,pregunta) values (91,'Proyectar obras de arquitectura')");
mysql_query("insert into test (num_preg,pregunta) values (92,'Enseñar a leer y escribir a adultos')");
mysql_query("insert into test (num_preg,pregunta) values (93,'Analizar textos literarios en otro idioma')");
mysql_query("insert into test (num_preg,pregunta) values (94,'Controlar a pacientes en salas de cuidados intensivos')");
mysql_query("insert into test (num_preg,pregunta) values (95,'Realizar trabajos de pintura mural')");
mysql_query("insert into test (num_preg,pregunta) values (96,'Trabajar con telescopios')");
mysql_query("insert into test (num_preg,pregunta) values (97,'Instruir a alumnos ciegos y/o sordos')");
mysql_query("insert into test (num_preg,pregunta) values (98,'Conocer diferentes estilos de arquitectónicos')");
mysql_query("insert into test (num_preg,pregunta) values (99,'Investigar el origen y evolución del universo')");
mysql_query("insert into test (num_preg,pregunta) values (100,'Capacitar a dirigentes políticos')");
mysql_query("insert into test (num_preg,pregunta) values (101,'Realizar tareas contables')");
mysql_query("insert into test (num_preg,pregunta) values (102,'Realizar trabajos de cerámica artesanal')");
mysql_query("insert into test (num_preg,pregunta) values (103,'Escuchar grabaciones en otro idioma')");
mysql_query("insert into test (num_preg,pregunta) values (104,'Trabajar en un laboratorio de física')");
mysql_query("insert into test (num_preg,pregunta) values (105,'Defender a acusados en un juicio')");
mysql_query("insert into test (num_preg,pregunta) values (106,'Componer música')");
mysql_query("insert into test (num_preg,pregunta) values (107,'Elaborar planes de desarrollo económico')");
mysql_query("insert into test (num_preg,pregunta) values (108,'Organizar actividades recreativas para ancianos')");
mysql_query("insert into test (num_preg,pregunta) values (109,'Investigar la atmósfera extraterrestre')");
mysql_query("insert into test (num_preg,pregunta) values (110,'Planificar actividades en la administración pública')");
mysql_query("insert into test (num_preg,pregunta) values (111,'Leer revistas de matemática')");
mysql_query("insert into test (num_preg,pregunta) values (112,'Analizar las características de dialectos indígenas')");
mysql_query("insert into test (num_preg,pregunta) values (113,'Filmar películas documentales')");
mysql_query("insert into test (num_preg,pregunta) values (114,'Trabajar en centros de cómputo')");
mysql_query("insert into test (num_preg,pregunta) values (115,'Investigar la mitología griega')");
mysql_query("insert into test (num_preg,pregunta) values (116,'Decorar interiores y exteriores')");
mysql_query("insert into test (num_preg,pregunta) values (117,'Analizar y comentar la actividad política')");
mysql_query("insert into test (num_preg,pregunta) values (118,'Reconocer los diferentes instrumentos de una orquesta')");
mysql_query("insert into test (num_preg,pregunta) values (119,'Investigar el movimiento de los átomos')");
mysql_query("insert into test (num_preg,pregunta) values (120,'Investigar los factores que modifican la producción láctea')");
mysql_query("insert into test (num_preg,pregunta) values (121,'Realizar estudios radiológicos')");
mysql_query("insert into test (num_preg,pregunta) values (122,'Organizar y administrar empresas')");
mysql_query("insert into test (num_preg,pregunta) values (123,'Recolectar muestras de rocas')");
mysql_query("insert into test (num_preg,pregunta) values (124,'Determinar la edad de los fósiles')");
mysql_query("insert into test (num_preg,pregunta) values (125,'Ser docente de caligrafía y/o dibujo')");
mysql_query("insert into test (num_preg,pregunta) values (126,'Efectuar disecciones de cadáveres')");
mysql_query("insert into test (num_preg,pregunta) values (127,'Leer y analizar textos históricos')");
mysql_query("insert into test (num_preg,pregunta) values (128,'Realizar análisis de materia prima')");
mysql_query("insert into test (num_preg,pregunta) values (129,'Fabricar materiales plásticos y fibras artificiales')");
mysql_query("insert into test (num_preg,pregunta) values (130,'Aprender a efectuar análisis de sangre')");
mysql_query("insert into test (num_preg,pregunta) values (131,'Diagnosticar problemas psicológicos')");
mysql_query("insert into test (num_preg,pregunta) values (132,'Analizar el proceso de formación de las nubes')");
mysql_query("insert into test (num_preg,pregunta) values (133,'Reparar televisores')");
mysql_query("insert into test (num_preg,pregunta) values (134,'Trabajar en clínicas, hospitales y servicios de salud')");
mysql_query("insert into test (num_preg,pregunta) values (135,'Elaborar programas de computación para resolver problemas técnicos')");
mysql_query("insert into test (num_preg,pregunta) values (136,'Inspeccionar construcciones de hormigón armado')");
mysql_query("insert into test (num_preg,pregunta) values (137,'Armar circuitos eléctricos')");
mysql_query("insert into test (num_preg,pregunta) values (138,'Investigar el empleo de la energía nuclear')");
mysql_query("insert into test (num_preg,pregunta) values (139,'Realizar entrevistas con presos y su grupo familiar')");
mysql_query("insert into test (num_preg,pregunta) values (140,'Hacer evaluaciones de daños de edificios')");
mysql_query("insert into test (num_preg,pregunta) values (141,'Interpretar un instrumento musical')");
mysql_query("insert into test (num_preg,pregunta) values (142,'Determinar causas de deserción escolar')");
mysql_query("insert into test (num_preg,pregunta) values (143,'Ayudar a encontrar empleo a jóvenes y/o discapacitados')");
mysql_query("insert into test (num_preg,pregunta) values (144,'Trabajar elementos de geometría')");
mysql_query("insert into test (num_preg,pregunta) values (145,'Ayudar a personas con problemas emocionales')");
mysql_query("insert into test (num_preg,pregunta) values (146,'Adquirir elementos de álgebra')");
mysql_query("insert into test (num_preg,pregunta) values (147,'Analizar la situación económico-financiera de una empresa')");
mysql_query("insert into test (num_preg,pregunta) values (148,'Participar en actividades políticas')");
mysql_query("insert into test (num_preg,pregunta) values (149,'Tomar fotografías para ilustrar artículos periodísticos ')");
mysql_query("insert into test (num_preg,pregunta) values (150,'Construir puentes')");

	}

function registrarUserAdm(){
      // $pass = hash('md5', 'cecytem.2018');
	echo mysql_query("insert into usuario (user,pss,rol) values ('root',MD5('cecytem.2018'),'admin')");
      echo "Usuario adminisgtrador: root, Password: cecytem.2018";
}


//registrarUserAdm();
// registrarPreguntas();
// registraAreas();
// registraPuntaje_percentil();
// registraPA();

echo "Registro exitoso";




?>